---
abstract: 'Infinite impulse response and recursive filters'
author:
  - 'John Lapeyre <jlapeyre@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-DSP-Iir
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  PDL: 0
version: 0.002
