--- #YAML:1.0
name:               PDL-DSP-Iir
version:            0.001
abstract:           Infinite impulse response and recursive filters
author:
    - John Lapeyre <jlapeyre@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:  0
    PDL:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
